In [8]:
import networkx as nx
import networkx.algorithms.bipartite as bipartite
import math
from prettytable import PrettyTable
import matplotlib.pyplot as plt
import numpy as np
import os
%matplotlib inline


In [2]:
G = nx.davis_southern_women_graph()



In [3]:
G = nx.davis_southern_women_graph()
women = ["Evelyn Jefferson",
             "Laura Mandeville",
             "Theresa Anderson",
             "Brenda Rogers",
             "Charlotte McDowd",
             "Frances Anderson",
             "Eleanor Nye",
             "Pearl Oglethorpe",
             "Ruth DeSand",
             "Verne Sanderson",
             "Myra Liddel",
             "Katherina Rogers",
             "Sylvia Avondale",
             "Nora Fayette",
             "Helen Lloyd",
             "Dorothy Murchison",
             "Olivia Carleton",
             "Flora Price"]
clubs = ["E1",
              "E2",
              "E3",
              "E4",
              "E5",
              "E6",
              "E7",
              "E8",
              "E9",
              "E10",
              "E11",
              "E12",
              "E13",
              "E14"]


print(bipartite.biadjacency_matrix(G,women,clubs))


  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 7)	1
  (0, 8)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (1, 4)	1
  (1, 5)	1
  (1, 6)	1
  (1, 7)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	1
  (2, 4)	1
  (2, 5)	1
  (2, 6)	1
  (2, 7)	1
  (2, 8)	1
  (3, 0)	1
  (3, 2)	1
  :	:
  (12, 7)	1
  (12, 8)	1
  (12, 9)	1
  (12, 11)	1
  (12, 12)	1
  (12, 13)	1
  (13, 5)	1
  (13, 6)	1
  (13, 8)	1
  (13, 9)	1
  (13, 10)	1
  (13, 11)	1
  (13, 12)	1
  (13, 13)	1
  (14, 6)	1
  (14, 7)	1
  (14, 9)	1
  (14, 10)	1
  (14, 11)	1
  (15, 7)	1
  (15, 8)	1
  (16, 8)	1
  (16, 10)	1
  (17, 8)	1
  (17, 10)	1


In [10]:
adj_mat = np.loadtxt(open("adj_mat.csv", "rb"), delimiter=",")

In [15]:
a = adj_mat
b = np.matrix.transpose(adj_mat)


print(np.matmul(a,b))

[[ 8.  6.  7.  6.  3.  4.  3.  3.  3.  2.  2.  2.  2.  2.  1.  2.  1.  1.]
 [ 6.  7.  6.  6.  3.  4.  4.  2.  3.  2.  1.  1.  2.  2.  2.  1.  0.  0.]
 [ 7.  6.  8.  6.  4.  4.  4.  3.  4.  3.  2.  2.  3.  3.  2.  2.  1.  1.]
 [ 6.  6.  6.  7.  4.  4.  4.  2.  3.  2.  1.  1.  2.  2.  2.  1.  0.  0.]
 [ 3.  3.  4.  4.  4.  2.  2.  0.  2.  1.  0.  0.  1.  1.  1.  0.  0.  0.]
 [ 4.  4.  4.  4.  2.  4.  3.  2.  2.  1.  1.  1.  1.  1.  1.  1.  0.  0.]
 [ 3.  4.  4.  4.  2.  3.  4.  2.  3.  2.  1.  1.  2.  2.  2.  1.  0.  0.]
 [ 3.  2.  3.  2.  0.  2.  2.  3.  2.  2.  2.  2.  2.  2.  1.  2.  1.  1.]
 [ 3.  3.  4.  3.  2.  2.  3.  2.  4.  3.  2.  2.  3.  2.  2.  2.  1.  1.]
 [ 2.  2.  3.  2.  1.  1.  2.  2.  3.  4.  3.  3.  4.  3.  3.  3.  1.  1.]
 [ 2.  1.  2.  1.  0.  1.  1.  2.  2.  3.  4.  4.  4.  3.  3.  4.  1.  1.]
 [ 2.  1.  2.  1.  0.  1.  1.  2.  2.  3.  4.  6.  6.  5.  5.  4.  1.  1.]
 [ 2.  2.  3.  2.  1.  1.  2.  2.  3.  4.  4.  6.  7.  6.  6.  4.  1.  1.]
 [ 2.  2.  3.  2.  1.  1.